import { useSEO } from '@/hooks/use-seo';

type LegalType = 'privacy' | 'terms' | 'disclaimer';
const content: Record<LegalType, { title: string; description: string; sections: { heading: string; text: string }[] }> = {
  privacy: { title: 'سياسة الخصوصية', description: 'كيف تتعامل أوفي الذكية مع بيانات التواصل وطلبات الخدمات.', sections: [{ heading: 'البيانات التي نتعامل معها', text: 'قد نتعامل مع بيانات التواصل وبيانات المنشأة والمستندات التي تقدمها لنا لغرض دراسة الطلب والتواصل والمتابعة. نطلب الحد اللازم من البيانات بحسب الخدمة.' }, { heading: 'استخدام البيانات وحمايتها', text: 'نستخدم البيانات لتقديم الخدمة والتواصل بشأنها وتنظيم الملف، ونقصر الوصول عليها على من تقتضي مهمته ذلك. يرجى عدم إرسال بيانات حساسة عبر قنوات غير آمنة.' }, { heading: 'مشاركة البيانات', text: 'لا نشارك البيانات إلا بالقدر الذي يلزم لتنفيذ الطلب أو عند وجود التزام نظامي أو موافقة مناسبة. تظل قرارات الجهات الرسمية وإجراءاتها ضمن صلاحياتها.' }, { heading: 'التحديثات', text: 'قد نحدّث هذه السياسة عند تغير طريقة العمل أو المتطلبات ذات العلاقة.' }] },
  terms: { title: 'الشروط والأحكام', description: 'الشروط العامة للاستفادة من خدمات أوفي الذكية.', sections: [{ heading: 'نطاق الخدمة', text: 'تقدم أوفي الذكية خدمات تنظيم ومتابعة وإسناد إداري للطلبات والخدمات المعلنة، وفق ما يتم الاتفاق عليه لكل حالة.' }, { heading: 'قرارات الجهات المختصة', text: 'تساعد أوفي الذكية في تجهيز الطلب ومتابعته، ولا تضمن القبول أو الإصدار أو أي قرار. الاعتماد النهائي والقرار يبقيان للجهة الحكومية أو التنظيمية المختصة.' }, { heading: 'الرسوم والمعلومات', text: 'الرسوم الحكومية منفصلة عن أتعاب الخدمة ما لم ينص عرض أو اتفاق مكتوب على خلاف ذلك. قد تتغير المعلومات والمتطلبات والرسوم أو الإجراءات، ويجب التحقق من المصدر الرسمي قبل التنفيذ.' }, { heading: 'مسؤولية العميل', text: 'يلتزم العميل بتقديم معلومات ووثائق صحيحة ومحدثة وبالحصول على الصلاحيات اللازمة للتقديم أو المتابعة.' }] },
  disclaimer: { title: 'إخلاء المسؤولية', description: 'تنبيه بشأن طبيعة المعلومات والخدمات في موقع أوفي الذكية.', sections: [{ heading: 'معلومات توعوية', text: 'المحتوى المنشور للتوعية العامة ولا يمثل استشارة قانونية أو ضريبية أو تنظيمية مخصصة، ولا يحل محل الرجوع إلى المختص أو المصدر الرسمي.' }, { heading: 'المتابعة وليست اعتماداً', text: 'تدير أوفي الذكية وتتابع الخدمات والطلبات بحسب نطاق العمل، بينما يظل القبول والاعتماد وقرار الجهة ضمن صلاحية الجهة المختصة وحدها.' }, { heading: 'تغير المعلومات', text: 'قد تتغير الإجراءات أو المتطلبات أو الرسوم الحكومية أو المعلومات المنشورة دون إشعار. الرسوم الحكومية منفصلة ما لم يذكر خلاف ذلك صراحةً.' }] },
};

export default function LegalPage({ type }: { type: LegalType }) {
  const page = content[type];
  useSEO({ title: page.title, description: page.description });
  return <div className="py-14 bg-background" dir="rtl"><main className="container mx-auto px-4 sm:px-6 lg:px-8 max-w-4xl"><header className="mb-10 border-b border-border pb-7"><p className="text-primary font-medium">أوفي الذكية</p><h1 className="text-4xl font-bold text-secondary mt-2">{page.title}</h1><p className="text-muted-foreground mt-4 leading-7">{page.description}</p></header><div className="space-y-8">{page.sections.map((section) => <section key={section.heading}><h2 className="text-2xl font-bold text-secondary mb-3">{section.heading}</h2><p className="leading-8 text-muted-foreground">{section.text}</p></section>)}</div></main></div>;
}